---
# install tasks file for mindflayer-openldap

- name: Declare and enable ltb yum repository
  ansible.builtin.template:
    src: ltb_repo.j2
    dest: /etc/yum.repos.d/ltb-project.repo

- name: Download ltb repo gpg key
  ansible.builtin.get_url:
    url: "{{ ltb_repo_remote_gpgkey }}"
    dest: "{{ ltb_repo_gpgkey | regex_replace('^file://', '') }}"

- name: Import ltb repo gpg key to rpm database
  ansible.builtin.rpm_key:
    key: "{{ ltb_repo_remote_gpgkey }}"
      
- name: Install openldap LTB 2.5 rpms
  ansible.builtin.yum:
    name: 
      - openldap-ltb
      - openldap-ltb-contrib-overlays
      - openldap-ltb-mdb-utils
    state: installed

- name: Install rsyslog if required
  ansible.builtin.yum:
    name: rsyslog
    state: installed

- name: Check rsyslog is running and enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Create openldap dedicated file system
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: ug+rw
    owner: ldap
    group: ldap
    setype: usr_t
  loop:
    - "{{ base_dir }}"
    - "{{ base_dir }}/{{ data_dir }}"
    - "{{ base_dir }}/{{ backup_dir }}"

- name: Create openldap log file system
  ansible.builtin.file:
    path: "{{ base_dir }}/{{ log_dir }}"
    state: directory
    mode: ug+rw
    owner: ldap
    group: ldap
    setype: var_log_t

- name: Add slapd-cli script and other openldap utilities in root PATH
  ansible.builtin.blockinfile:
    block: |
      PATH=$PATH:/usr/local/openldap/sbin
      export PATH
    marker: "# {mark} OPENLDAP-UTILITIES ANSIBLE MANAGED BLOCK"
    path: ~/.bashrc
    state: present

- name: Edit slapd-cli.conf file - BACKUP_PATH
  ansible.builtin.lineinfile:
    path: /usr/local/openldap/etc/openldap/slapd-cli.conf
    regexp: "^BACKUP_PATH"
    line: "BACKUP_PATH=\"{{ base_dir }}/{{ backup_dir }}\""

- name: Reconfigure rsyslog openldap logs collection
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: "^local4"
    line: "if $syslogfacility-text == 'local4' and $programname == 'slapd' then  -{{ base_dir  }}/{{ log_dir }}/{{ log_file }}"
  notify:
    - restart rsyslog 

- name: Reconfigure openldap logrotate
  ansible.builtin.lineinfile:
    path: /etc/logrotate.d/openldap
    regexp: "^/var/log/openldap.log"
    line: "{{ base_dir  }}/{{ log_dir }}/{{ log_file }} {"

- name: Render openldap backup script
  ansible.builtin.template:
    src: backup_script.j2
    dest: "{{ base_dir }}/{{ backup_dir }}/backup_script.sh"
    mode: ug+rwx

- name: Configure backup in root crontab
  ansible.builtin.cron:
    name: Openldap backup job
    job: "{{ base_dir }}/{{ backup_dir }}/backup_script.sh"
    month: "{{ backup_cron_month }}"
    day: "{{ backup_cron_day }}"
    weekday: "{{ backup_cron_weekday }}"
    hour: "{{ backup_cron_hour }}"
    minute: "{{ backup_cron_minute }}"
    state: present

- name: Render ldif for mdb database location update
  ansible.builtin.template:
    src: olcDbDirectory.j2
    dest: "{{ base_dir }}/{{ backup_dir }}/olcDbDirectory.ldif"

- name: Update mdb database location in openldap
  ansible.builtin.command:
    cmd: "ldapmodify -Y EXTERNAL -H ldapi://%2Fvar%2Frun%2Fslapd%2Fldapi -f {{ base_dir }}/{{ backup_dir }}/olcDbDirectory.ldif"

- name: Clean up unused files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ base_dir }}/{{ backup_dir }}/olcDbDirectory.ldif"
    - /usr/local/openldap/var/openldap-data/data.mdb
    - /usr/local/openldap/var/openldap-data/lock.mdb
    - /var/log/openldap.log
...
