---
# main tasks file for mindflayer-openldap

- name: display role startup message
  ansible.builtin.debug:
    msg: "Starting mindflayer-openldap Ansible role execution"

- name: execute installation tasks if required
  include_tasks: install.yml
  when: do_install

- name: execute uninstallation tasks if required
  include_tasks: uninstall.yml
  when: do_uninstall

- name: execute configuration tasks if required
  include_tasks: configure.yml
  when: do_configure

...
